Create Domain
bmstu-itstech/itsreg-auth pull request #1
Opened 2024-08-02 19:19 UTC by viacheslavek

2024-08-02 19:35 UTC, zhikh23 requested changes
Классно, мне очень понравилось! Но нужно исправить замечания и можно будет мерджить

2024-08-02 19:35 UTC, zhikh23 commented on internal/domain/entity/user.go
> +	if user.Id != value.UnknownUserId {
Сразу видно, что взято из моего репозитория)

Собственно, наверное у тебя возник вопрос, зачем эта проверка. Дело в том, что 0 - очень часто значение по умолчанию. Postgres уже гарантирует, что SERIAL ключ не будет равен нулю, а значит, что встретив 0 - мы скорее всего где-то пропустили заполнение всех полей структуры и оно осталось дефолтным. Иногда нуль можно использовать в качестве особого значения.

Поэтому я выношу 0 в обычной инициализации, как ошибку. 

Собственно, из этого и следует, что ошибка user already exitsts несколько странной) Плюс, желательно выносить ошибки в var Err<что-то> = errors.New, если только это совсем не внутрячковая ошибка. Почему? Переиспользование и, в теории, обработка

2024-08-02 19:35 UTC, zhikh23 commented on internal/domain/value/email.go
> +		is.Email,
Всё классно, это не ошибка.
Просто однажды я наступил на эти грабли)

Дело в том, что is.Email работает... странно. Эта функция каким-то образом проверяет существование почты?.. В общем, иногда она дает ошибки. Если вдруг столкнешься со странными ошибка невалидной почты, то замени на RegEx)

В целом, можно оставить.

2024-08-02 19:35 UTC, zhikh23 commented on internal/domain/value/password.go
> +	err := bcrypt.CompareHashAndPassword(hash, []byte(password))
Отсутствует обработка ошибки, кроме той, что `ErrMismatchedHashAndPassword`. При этом, здесь это сильно критично: в случае, если эта функция выкинет _другую_ ошибку, вернется `true` и пользователь зайдет, даже если пароли не совпали!

2024-08-02 19:36 UTC, zhikh23 commented on internal/domain/value/email.go
> +		is.Email,
Как прочтешь, закроешь как solved)

2024-08-02 19:36 UTC, zhikh23 commented on internal/domain/entity/user.go
> +	if user.Id != value.UnknownUserId {
Как прочтешь, можешь закрыть как solved.
Либо везде заменить `fmt.Errorf` на `errors.New`

2024-08-02 19:44 UTC, viacheslavek commented on internal/domain/value/email.go
> +		is.Email,
Да, это очень хитрая валидация, она смотрит, что указаный домен (который после собаки) есть в глобальных почтовых доменах. И из-за этого библиотеки по генерации тестовых данных (например, почт), часто не подходят. Я изучил это в ownere и даже сделал костыль с ретраем почты)) Вот тут: https://github.com/viacheslavek/grpcauth/blob/9fc71dac0c99f9db18231b00b38e98d93ae0117a/auth/tests/full_cycle_owner_test.go#L44

2024-08-02 19:45 UTC, viacheslavek commented on internal/domain/value/password.go
> +	err := bcrypt.CompareHashAndPassword(hash, []byte(password))
Пупупу, а это мой огромный косяк

2024-08-19 15:08 UTC, merged

2024-08-20 07:18 UTC, zhikh23 approved these changes